// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsxUb-wQJAd6u3KQRqg_ZjtfAAHhBMeOU',
    appId: '1:516044434722:web:d28e4f6ab9d4ac5838497b',
    messagingSenderId: '516044434722',
    projectId: 'smart-transist-guardian',
    authDomain: 'smart-transist-guardian.firebaseapp.com',
    storageBucket: 'smart-transist-guardian.firebasestorage.app',
    measurementId: 'G-H88THZQ5PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpcZubY4c61E_BHuQlgVhOeqdTYIigDvM',
    appId: '1:516044434722:android:fa80739899a2551538497b',
    messagingSenderId: '516044434722',
    projectId: 'smart-transist-guardian',
    storageBucket: 'smart-transist-guardian.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzHZCcMU9fMeQVeKW93nCQdSCLTmuyU-A',
    appId: '1:516044434722:ios:091095fb2440d89a38497b',
    messagingSenderId: '516044434722',
    projectId: 'smart-transist-guardian',
    storageBucket: 'smart-transist-guardian.firebasestorage.app',
    iosBundleId: 'com.example.smartTransistGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzHZCcMU9fMeQVeKW93nCQdSCLTmuyU-A',
    appId: '1:516044434722:ios:091095fb2440d89a38497b',
    messagingSenderId: '516044434722',
    projectId: 'smart-transist-guardian',
    storageBucket: 'smart-transist-guardian.firebasestorage.app',
    iosBundleId: 'com.example.smartTransistGuardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsxUb-wQJAd6u3KQRqg_ZjtfAAHhBMeOU',
    appId: '1:516044434722:web:327ab5e77a18108538497b',
    messagingSenderId: '516044434722',
    projectId: 'smart-transist-guardian',
    authDomain: 'smart-transist-guardian.firebaseapp.com',
    storageBucket: 'smart-transist-guardian.firebasestorage.app',
    measurementId: 'G-8859M9Y8RC',
  );
}
